sudo: false
language: node_js
node_js:
  - "8"
install:
  - npm install --global --production yaspeller markdown-link-check
  # download dictionary from atsd repository for merging
  - wget https://raw.githubusercontent.com/axibase/atsd/master/.spelling
  # generate dictionary in JSON format
  - cat .spelling .dictionary | awk '{$1=$1};1' | sort -u | jq -csR 'split("\n")' > .yaspeller-dictionary.json
script: 
  - yaspeller --max-requests 10 --dictionary .yaspeller-dictionary.json -e ".md" ./
  - bash get_changed_md_files.sh | xargs -d '\n' -n1 markdown-link-check
cache:
  directories:
    - $(npm config get prefix)/lib/node_modules
notifications:
  webhooks: https://apps.axibase.com/api/v1/messages/wk-travis-ci/travis-ci
