sudo: false
language: node_js
node_js:
  - "8"
install:
  - npm install -g yaspeller
script: 
  - yaspeller -e ".md" ./
  - find . -name \*.md -exec markdown-link-check {} \;
cache:
  directories:
    - "node_modules"
